// flow-typed signature: 64843653f8bd6192877afe2c0f04e344
// flow-typed version: <<STUB>>/apollo-cache-persist_v0.1.1/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-cache-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-cache-persist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-cache-persist/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/Cache' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/CachePersistor' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/Log' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/onAppBackground' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/onAppBackground.native' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/onCacheWrite' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/persistCache' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/Persistor' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/Storage' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/Trigger' {
  declare module.exports: any;
}

declare module 'apollo-cache-persist/types/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-cache-persist/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-cache-persist/bundle.umd'>;
}
declare module 'apollo-cache-persist/Cache.js' {
  declare module.exports: $Exports<'apollo-cache-persist/Cache'>;
}
declare module 'apollo-cache-persist/CachePersistor.js' {
  declare module.exports: $Exports<'apollo-cache-persist/CachePersistor'>;
}
declare module 'apollo-cache-persist/index' {
  declare module.exports: $Exports<'apollo-cache-persist'>;
}
declare module 'apollo-cache-persist/index.js' {
  declare module.exports: $Exports<'apollo-cache-persist'>;
}
declare module 'apollo-cache-persist/Log.js' {
  declare module.exports: $Exports<'apollo-cache-persist/Log'>;
}
declare module 'apollo-cache-persist/onAppBackground.js' {
  declare module.exports: $Exports<'apollo-cache-persist/onAppBackground'>;
}
declare module 'apollo-cache-persist/onAppBackground.native.js' {
  declare module.exports: $Exports<'apollo-cache-persist/onAppBackground.native'>;
}
declare module 'apollo-cache-persist/onCacheWrite.js' {
  declare module.exports: $Exports<'apollo-cache-persist/onCacheWrite'>;
}
declare module 'apollo-cache-persist/persistCache.js' {
  declare module.exports: $Exports<'apollo-cache-persist/persistCache'>;
}
declare module 'apollo-cache-persist/Persistor.js' {
  declare module.exports: $Exports<'apollo-cache-persist/Persistor'>;
}
declare module 'apollo-cache-persist/Storage.js' {
  declare module.exports: $Exports<'apollo-cache-persist/Storage'>;
}
declare module 'apollo-cache-persist/Trigger.js' {
  declare module.exports: $Exports<'apollo-cache-persist/Trigger'>;
}
declare module 'apollo-cache-persist/types/index.js' {
  declare module.exports: $Exports<'apollo-cache-persist/types/index'>;
}
