// flow-typed signature: 01985e1f154433d8f9e62af1cc6a32ce
// flow-typed version: <<STUB>>/graphql-anywhere_v4.1.8/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-anywhere'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-anywhere' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-anywhere/lib/async' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/bundle' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/bundle.min' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/graphql-async' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/graphql' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/index' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/utilities' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/rollup.async.config' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-anywhere/lib/async.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/async'>;
}
declare module 'graphql-anywhere/lib/bundle.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/bundle'>;
}
declare module 'graphql-anywhere/lib/bundle.min.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/bundle.min'>;
}
declare module 'graphql-anywhere/lib/bundle.umd.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/bundle.umd'>;
}
declare module 'graphql-anywhere/lib/graphql-async.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/graphql-async'>;
}
declare module 'graphql-anywhere/lib/graphql.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/graphql'>;
}
declare module 'graphql-anywhere/lib/index.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/index'>;
}
declare module 'graphql-anywhere/lib/utilities.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/utilities'>;
}
declare module 'graphql-anywhere/rollup.async.config.js' {
  declare module.exports: $Exports<'graphql-anywhere/rollup.async.config'>;
}
declare module 'graphql-anywhere/rollup.config.js' {
  declare module.exports: $Exports<'graphql-anywhere/rollup.config'>;
}
