// flow-typed signature: 6aeab0938f304eeac40c6ba9599347fc
// flow-typed version: <<STUB>>/react-router-navigation_v1.0.0-rc.4/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-navigation/flow-typed/npm/jest_v18.x.x' {
  declare module.exports: any;
}

declare module 'react-router-navigation/flow-typed/npm/react-addons-test-utils_v15.x.x' {
  declare module.exports: any;
}

declare module 'react-router-navigation/flow-typed/npm/react-native-tab-view_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-navigation/flow-typed/npm/react-router_v4.x.x' {
  declare module.exports: any;
}

declare module 'react-router-navigation/flow-typed/react-native' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/BottomNavigation' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/Card' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/CardStack' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/DefaultRenderer' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/HistoryUtils' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/NavBar' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/Navigation' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/SceneView' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/StackUtils' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/Tab' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/TabBarBottom' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/Tabs' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/TabStack' {
  declare module.exports: any;
}

declare module 'react-router-navigation/modules/TypeDefinitions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-navigation/flow-typed/npm/jest_v18.x.x.js' {
  declare module.exports: $Exports<'react-router-navigation/flow-typed/npm/jest_v18.x.x'>;
}
declare module 'react-router-navigation/flow-typed/npm/react-addons-test-utils_v15.x.x.js' {
  declare module.exports: $Exports<'react-router-navigation/flow-typed/npm/react-addons-test-utils_v15.x.x'>;
}
declare module 'react-router-navigation/flow-typed/npm/react-native-tab-view_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-navigation/flow-typed/npm/react-native-tab-view_vx.x.x'>;
}
declare module 'react-router-navigation/flow-typed/npm/react-router_v4.x.x.js' {
  declare module.exports: $Exports<'react-router-navigation/flow-typed/npm/react-router_v4.x.x'>;
}
declare module 'react-router-navigation/flow-typed/react-native.js' {
  declare module.exports: $Exports<'react-router-navigation/flow-typed/react-native'>;
}
declare module 'react-router-navigation/index' {
  declare module.exports: $Exports<'react-router-navigation'>;
}
declare module 'react-router-navigation/index.js' {
  declare module.exports: $Exports<'react-router-navigation'>;
}
declare module 'react-router-navigation/modules/BottomNavigation.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/BottomNavigation'>;
}
declare module 'react-router-navigation/modules/Card.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/Card'>;
}
declare module 'react-router-navigation/modules/CardStack.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/CardStack'>;
}
declare module 'react-router-navigation/modules/DefaultRenderer.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/DefaultRenderer'>;
}
declare module 'react-router-navigation/modules/HistoryUtils.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/HistoryUtils'>;
}
declare module 'react-router-navigation/modules/NavBar.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/NavBar'>;
}
declare module 'react-router-navigation/modules/Navigation.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/Navigation'>;
}
declare module 'react-router-navigation/modules/SceneView.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/SceneView'>;
}
declare module 'react-router-navigation/modules/StackUtils.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/StackUtils'>;
}
declare module 'react-router-navigation/modules/Tab.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/Tab'>;
}
declare module 'react-router-navigation/modules/TabBarBottom.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/TabBarBottom'>;
}
declare module 'react-router-navigation/modules/Tabs.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/Tabs'>;
}
declare module 'react-router-navigation/modules/TabStack.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/TabStack'>;
}
declare module 'react-router-navigation/modules/TypeDefinitions.js' {
  declare module.exports: $Exports<'react-router-navigation/modules/TypeDefinitions'>;
}
