// flow-typed signature: 02c24b02b1b2bef01a3612d474c4851c
// flow-typed version: <<STUB>>/react-native-navigation_v2.0.2072/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-navigation/lib/src/adapters/Element' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/adapters/NativeCommandsSender' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/adapters/NativeCommandsSender.mock' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/adapters/NativeEventsReceiver' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/adapters/NativeEventsReceiver.mock' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/adapters/UniqueIdProvider' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/adapters/UniqueIdProvider.mock' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/commands/Commands' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/commands/Commands.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/commands/LayoutTreeCrawler' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/commands/LayoutTreeCrawler.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/commands/LayoutTreeParser' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/commands/LayoutTreeParser.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/commands/LayoutTypes' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/commands/OptionsProcessor' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/commands/OptionsProcessor.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/commands/SimpleLayouts' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/containers/ContainerRegistry' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/containers/ContainerRegistry.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/containers/ContainerWrapper' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/containers/ContainerWrapper.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/containers/Lifecycle' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/containers/Lifecycle.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/containers/Store' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/containers/Store.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/events/PrivateEventsListener' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/events/PrivateEventsListener.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/events/PublicEventsRegistry' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/events/PublicEventsRegistry.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/index' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/Navigation' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/containers/Container' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/containers/Container.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/containers/Root' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/containers/Root.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/containers/SideMenu' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/containers/SideMenu.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/BottomTab' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/BottomTab.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/BottomTabs' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/BottomTabs.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/Button' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/Button.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/NavigationOptions' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/NavigationOptions.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/TopBar' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/TopBar.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/TopTab' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/TopTab.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/TopTabs' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/src/params/options/TopTabs.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-navigation/lib/src/adapters/Element.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/adapters/Element'>;
}
declare module 'react-native-navigation/lib/src/adapters/NativeCommandsSender.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/adapters/NativeCommandsSender'>;
}
declare module 'react-native-navigation/lib/src/adapters/NativeCommandsSender.mock.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/adapters/NativeCommandsSender.mock'>;
}
declare module 'react-native-navigation/lib/src/adapters/NativeEventsReceiver.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/adapters/NativeEventsReceiver'>;
}
declare module 'react-native-navigation/lib/src/adapters/NativeEventsReceiver.mock.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/adapters/NativeEventsReceiver.mock'>;
}
declare module 'react-native-navigation/lib/src/adapters/UniqueIdProvider.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/adapters/UniqueIdProvider'>;
}
declare module 'react-native-navigation/lib/src/adapters/UniqueIdProvider.mock.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/adapters/UniqueIdProvider.mock'>;
}
declare module 'react-native-navigation/lib/src/commands/Commands.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/commands/Commands'>;
}
declare module 'react-native-navigation/lib/src/commands/Commands.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/commands/Commands.test'>;
}
declare module 'react-native-navigation/lib/src/commands/LayoutTreeCrawler.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/commands/LayoutTreeCrawler'>;
}
declare module 'react-native-navigation/lib/src/commands/LayoutTreeCrawler.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/commands/LayoutTreeCrawler.test'>;
}
declare module 'react-native-navigation/lib/src/commands/LayoutTreeParser.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/commands/LayoutTreeParser'>;
}
declare module 'react-native-navigation/lib/src/commands/LayoutTreeParser.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/commands/LayoutTreeParser.test'>;
}
declare module 'react-native-navigation/lib/src/commands/LayoutTypes.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/commands/LayoutTypes'>;
}
declare module 'react-native-navigation/lib/src/commands/OptionsProcessor.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/commands/OptionsProcessor'>;
}
declare module 'react-native-navigation/lib/src/commands/OptionsProcessor.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/commands/OptionsProcessor.test'>;
}
declare module 'react-native-navigation/lib/src/commands/SimpleLayouts.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/commands/SimpleLayouts'>;
}
declare module 'react-native-navigation/lib/src/containers/ContainerRegistry.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/containers/ContainerRegistry'>;
}
declare module 'react-native-navigation/lib/src/containers/ContainerRegistry.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/containers/ContainerRegistry.test'>;
}
declare module 'react-native-navigation/lib/src/containers/ContainerWrapper.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/containers/ContainerWrapper'>;
}
declare module 'react-native-navigation/lib/src/containers/ContainerWrapper.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/containers/ContainerWrapper.test'>;
}
declare module 'react-native-navigation/lib/src/containers/Lifecycle.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/containers/Lifecycle'>;
}
declare module 'react-native-navigation/lib/src/containers/Lifecycle.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/containers/Lifecycle.test'>;
}
declare module 'react-native-navigation/lib/src/containers/Store.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/containers/Store'>;
}
declare module 'react-native-navigation/lib/src/containers/Store.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/containers/Store.test'>;
}
declare module 'react-native-navigation/lib/src/events/PrivateEventsListener.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/events/PrivateEventsListener'>;
}
declare module 'react-native-navigation/lib/src/events/PrivateEventsListener.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/events/PrivateEventsListener.test'>;
}
declare module 'react-native-navigation/lib/src/events/PublicEventsRegistry.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/events/PublicEventsRegistry'>;
}
declare module 'react-native-navigation/lib/src/events/PublicEventsRegistry.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/events/PublicEventsRegistry.test'>;
}
declare module 'react-native-navigation/lib/src/index.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/index'>;
}
declare module 'react-native-navigation/lib/src/Navigation.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/Navigation'>;
}
declare module 'react-native-navigation/lib/src/params/containers/Container.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/containers/Container'>;
}
declare module 'react-native-navigation/lib/src/params/containers/Container.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/containers/Container.test'>;
}
declare module 'react-native-navigation/lib/src/params/containers/Root.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/containers/Root'>;
}
declare module 'react-native-navigation/lib/src/params/containers/Root.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/containers/Root.test'>;
}
declare module 'react-native-navigation/lib/src/params/containers/SideMenu.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/containers/SideMenu'>;
}
declare module 'react-native-navigation/lib/src/params/containers/SideMenu.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/containers/SideMenu.test'>;
}
declare module 'react-native-navigation/lib/src/params/options/BottomTab.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/BottomTab'>;
}
declare module 'react-native-navigation/lib/src/params/options/BottomTab.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/BottomTab.test'>;
}
declare module 'react-native-navigation/lib/src/params/options/BottomTabs.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/BottomTabs'>;
}
declare module 'react-native-navigation/lib/src/params/options/BottomTabs.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/BottomTabs.test'>;
}
declare module 'react-native-navigation/lib/src/params/options/Button.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/Button'>;
}
declare module 'react-native-navigation/lib/src/params/options/Button.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/Button.test'>;
}
declare module 'react-native-navigation/lib/src/params/options/NavigationOptions.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/NavigationOptions'>;
}
declare module 'react-native-navigation/lib/src/params/options/NavigationOptions.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/NavigationOptions.test'>;
}
declare module 'react-native-navigation/lib/src/params/options/TopBar.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/TopBar'>;
}
declare module 'react-native-navigation/lib/src/params/options/TopBar.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/TopBar.test'>;
}
declare module 'react-native-navigation/lib/src/params/options/TopTab.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/TopTab'>;
}
declare module 'react-native-navigation/lib/src/params/options/TopTab.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/TopTab.test'>;
}
declare module 'react-native-navigation/lib/src/params/options/TopTabs.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/TopTabs'>;
}
declare module 'react-native-navigation/lib/src/params/options/TopTabs.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/src/params/options/TopTabs.test'>;
}
