// flow-typed signature: fb6f0a5aa2d3cabc766a4d6bb77d89f0
// flow-typed version: <<STUB>>/@expo/react-native-action-sheet_v1.0.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@expo/react-native-action-sheet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@expo/react-native-action-sheet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@expo/react-native-action-sheet/ActionSheet.android' {
  declare module.exports: any;
}

declare module '@expo/react-native-action-sheet/ActionSheet.ios' {
  declare module.exports: any;
}

declare module '@expo/react-native-action-sheet/ActionSheetProvider' {
  declare module.exports: any;
}

declare module '@expo/react-native-action-sheet/connectActionSheet' {
  declare module.exports: any;
}

// Filename aliases
declare module '@expo/react-native-action-sheet/ActionSheet.android.js' {
  declare module.exports: $Exports<'@expo/react-native-action-sheet/ActionSheet.android'>;
}
declare module '@expo/react-native-action-sheet/ActionSheet.ios.js' {
  declare module.exports: $Exports<'@expo/react-native-action-sheet/ActionSheet.ios'>;
}
declare module '@expo/react-native-action-sheet/ActionSheetProvider.js' {
  declare module.exports: $Exports<'@expo/react-native-action-sheet/ActionSheetProvider'>;
}
declare module '@expo/react-native-action-sheet/connectActionSheet.js' {
  declare module.exports: $Exports<'@expo/react-native-action-sheet/connectActionSheet'>;
}
declare module '@expo/react-native-action-sheet/index' {
  declare module.exports: $Exports<'@expo/react-native-action-sheet'>;
}
declare module '@expo/react-native-action-sheet/index.js' {
  declare module.exports: $Exports<'@expo/react-native-action-sheet'>;
}
